# Generated by Django 3.0.7 on 2020-06-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200616_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('link', models.CharField(max_length=124, primary_key=True, serialize=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
    ]
