# Generated by Django 3.0.7 on 2020-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200621_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
